apiVersion: ENC[AES256_GCM,data:UQY=,iv:4lwhWZD2u97aoXM22o1Mi6p+da0jar+sRYOIau6cAM8=,tag:4jSF2LA0HRKUINbn0rzHEA==,type:str]
kind: ENC[AES256_GCM,data:ygY+Ktt6,iv:svQ8g6UcRfjO82PEWyQiMsMQtEUxhkM8HckW5f2PIi4=,tag:kPSpYFHXE2SVg+EaR2rmcg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MvdOsuDQWiWySUHR7aw=,iv:o5+6O3GPn7/1bbEPNyU1IoQA8kUt+yqSdycCzIG7yS4=,tag:fX6nQVTjOYAXx8qLihDHrA==,type:str]
    namespace: ENC[AES256_GCM,data:WUdVG8cW,iv:EFG7vufHzu752kNUJrOC3fvS0AzHuTMsDyKUps//1s8=,tag:Gs0EnVsdUmhcsPwbtPX35Q==,type:str]
type: ENC[AES256_GCM,data:9m/+m+9W,iv:znYmED0bCsBTno7ukVIb5a9PDNkXemQIristFFii7dU=,tag:6NpH/JzhgyaMDaDBsYCbYw==,type:str]
stringData:
    db-username: ENC[AES256_GCM,data:b59WnE/V,iv:mHGOE1b1OGDaAySmwU0fkRiv3hFXYAGjNtVjopWnUq0=,tag:Xi4GwUYR7W6kMKmPEviCsA==,type:str]
    db-password: ENC[AES256_GCM,data:h52xPyQELSg0O1zgXxKaSJIUs1vIFDtTFwR82ffudjw=,iv:/NsAR36VMVlFrQWVw8uyBiQntFsxZhgiJ0LQ+XY8f5E=,tag:dWzf3fOvk+X3Wy26QcgwNQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSkNBbzNtMCsvTE1JOEln
            eFRNOUtEdXFONWVKZm1BLzNjYjBmRFBvV0VjCmdYUzV6cHFxS3ZlRWxuRFVncE9r
            VjNBT0JBU0xlR3pXNkQvT0pydlk3SWMKLS0tIDB4UkdSalI2aVJTNDRtUWR4dndT
            b08rOTV0SW1lOEdMZnBZNzZXNlFpUDgKIHmJ+NBsLsWpCB1hM0c5sif//Ne+Gih4
            Z8vliySzdhGUFixFAlO205GWPfAD1Yh1Fkq7d7CWTvECk1GO49rcHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pht0t0fr9gr8tf2vqm5y4s8lrg6g2xtql5m2xgzm4lv38mhaqfsslekwsa
    lastmodified: "2026-08-08T19:37:32Z"
    mac: ENC[AES256_GCM,data:Nvm8Di20GdiQlazOHw6by+4GvWPHcmpSFlSNAjp95nMycvdN/KmTkgLV+VXbXQ3w17A3HdLxGgAh8MnuFo/7nK7cC7GxgyXCh6VcRruQQ/dVvL22yQc27wjdhmEh4LlILny7rM9CVtHDf2BueeK7TRayZNkRuJRQUZdrCvWDlAE=,iv:7w8+zjPlajim81OoEKSU6uUSFtBJhBvu+hfYQI23Sms=,tag:UI2JP6PV3DRX3DBok24QtA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
