ldap_bind_password: ENC[AES256_GCM,data:qgmRtOMkcTpI,iv:fcnyphZY872ocOe751b3VCaQwky6/1SFXFkYp5MGPZI=,tag:b/RAe5sRSwFjTJD12diPvg==,type:str]
sops:
    age:
        - recipient: age1pht0t0fr9gr8tf2vqm5y4s8lrg6g2xtql5m2xgzm4lv38mhaqfsslekwsa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UFV6WTZ4ZGlZRUZOVDMv
            M2pReXdGMk8ybnFoM1c0VDRWdHhaaXlPVVNZCjUvQ09yaER5RE9OS0ovTFY3RnNN
            Tk9qdVNiU0daZ3FXcEZWRytnU2k0bW8KLS0tIGo0TG9Ta21jMFl3eUZUNW9iNjZu
            dWJCVXFHcHY0MzJxSC92RVZpMkdZaTgKxuqZdNPHE2SjpsVxxr53snL0kmQ+AoxV
            /nnrRIA2pz8jesC6A+hMwvbX57nFJQt1BvtfvnbW/8ji85vmIoJyGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T22:03:37Z"
    mac: ENC[AES256_GCM,data:Rjg5poe8IsS8ZrP77GxjPRGJ6sugnaO9vCwLW3i2yPGjSGZi+tlGAxrmWITfx0394U0Y+Im9Fis18jbWaWdYJcQzQVdQkxphD34H5r0zmenk3MO9xdCyOeoVDy/gOI5l2JmzcrpkwW1CMcJTaWAKns+WJ35Ggd71bqBX64gda3Y=,iv:Sanet1ojQhpgIQEb2ZUWjqxvF8kkqxOT37XWDmzJy+I=,tag:dBp0mvLzrizRL2Yyl2JXTQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
