apiVersion: ENC[AES256_GCM,data:FZc=,iv:RSWZkbX+OLMSgxs67o9XXUrqWaWMfpL//xF6SLfZFxU=,tag:015jx4fSr2IUkdDRo+dwzA==,type:str]
kind: ENC[AES256_GCM,data:46k7PFfK,iv:y2YbMBUiXpMvzaGHSPZ1Svj1bdbkx1QitDpfEwrWXYg=,tag:XyDoKJ5R2Qp0WzofmFD/5g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:l2lH1fx9MP/FDNIDehRYDlMyaA==,iv:aZhS25HSW8tQNVrcu5IujlgPizP8mTeapboghl3+k0k=,tag:zhIKawMnRjKo5fjvSW2vmQ==,type:str]
    namespace: ENC[AES256_GCM,data:zV0qn0TO9OrDlQ==,iv:GdC7iT1SOVXmdNh6ka5Gi3Dc3zMEOESz9et74jvPDKA=,tag:RHQ8k4J7mBD9K4I6sNyvQg==,type:str]
type: ENC[AES256_GCM,data:1MEs9sBX,iv:GKVFhFuVX338qXfKoF0DBHq8bJDTWOKg3z8c1qp2xMA=,tag:s4OmhYvDD/SWJ+Bmvt6nCw==,type:str]
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:xKHjklvxy709urJU+xvsB++OqipAgBcH90YIavJXsQlwWoKYB4JKHWbBpThuIKUnfrWm72a6IV5MTGHqHQfNRTztPg/+r28St9wqwm9lvpPsurbLJ2QvdFmypUJYPxNfHT50jjZ6NHSfxXxdOO3Jt5K+UiOLPY5Ucm/y/7MoypKQBNvxFDDjDxro01zvnqA+bHmm59wuzbBYvZWdsxIivSKLaiF0OEXG6GNZvZWiT8oeOFrXvjKAyl8kaoyBJ5vHFDDQvwH83DTVAQ1rPUU7N3Bb+amJDvinE7pKAcHdlewIsAT9vxx8ia0xloTQP89plm/Q68hbDnf+9ZhhIvBf6d8VPdaDdtKMDIG99+utvjQVBe4OP8Hr2q+1U1LGuBVO0K2EHgKmK2qN64epXLM+ozso/1Lj2lHz6FBkdf9Ve4NhV+BmOxqC/uNpvZylAsZwvEwP/ycnVprlysL7kdL1LUKA3w2St2pDiMfxw3+qeWONetgkElgb4o5n646ntsKw42ro3+ayeWGuDGn1jRxz3pebkZ4yV9oIueT/mGhoN4V536Bo+GH7gvaHh2rWP6mi4XSaCpO4vg0YTQJBVi+9ocw3Vh4EuEVe3bl8T6VtMw0yQmszh7bpdLWLNQIf14H2zB+AJMyjEaunoxsEPwuH1IrKlUl6afsSLVtZ3/lnrP3/LGqjztvxtBL5EO5sNvvZT+aYdqVAQtUVfkm02ut1+qz5PVpky8jq1tDTo0qLgSqmCFhCkMf/X1IAuJVIldQeey5wsHsIBQan8cD1CIl+rMLYOJvWkgqDMHtvp8B41eo+ju0PS0s40Ok9h6hDCmjiGOyUksZQKgyt+1LdXr2ipX7ky73GDlV3wPqRps6vnA5flEZ0uB7T7T1XypbB1pC5UHk01mmaWVQpon4l2tibmGPbMwL9,iv:PoKBvCU7l14hKzyfybdyaeiEzo7mVSgCw0bC4tcfj/A=,tag:W9WUM+fTLRJRwRpCVJy/Iw==,type:str]
sops:
    age:
        - recipient: age1pht0t0fr9gr8tf2vqm5y4s8lrg6g2xtql5m2xgzm4lv38mhaqfsslekwsa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2QzRydEduUGU1Y2RHV044
            bEFmeDhLUC85dzl2OW1SaDNGRkw4eDNjNDBFCnUyQ3ZPUE9ubmh4NCtmZE0xL3Fi
            TWt6SDFqOTVaTXJKb2xZQVRmZ3pGbFEKLS0tIEQvS0l5d0xDczRZUnJZRnF5NVhm
            NXRSQ3ZOcFh0WWVhRkQycXRzTW1LVk0K8kNqr1+5jwiB5en5KRjYHXZgBFuzlyC3
            nTqQl0TszOMzjmr4vAPEynE4AgwrggdbmNErCZkRZxlxNyBJlqveyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T02:26:08Z"
    mac: ENC[AES256_GCM,data:nevi3pe7VflDVitqa1dtCD9eynFMBR9gQtkjrl4yQag9iiTQx3nBqdLGW5zpRt/F2kofa7nCXXvmvAJus9ggrbSklrl+ux/LQeBx+zp6AGhpHxRyRkS4bSeriPt5izxCqeEjGOR+DD/hs+ub992VE4r+uRy6UCgQ2dpgjD62IDI=,iv:SC2H+yxtA9Jp9aBoPmUVovbZw8gJgKx9BovdKMa9Irg=,tag:DGHvUKP2ApVQhU0zMZRK/Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
