apiVersion: ENC[AES256_GCM,data:iCI=,iv:eG8d9wO6tOhF2Z4SEOITO4F9XGp1riLZfovFs3it6Cg=,tag:OfYJ1lK2+VFW8m3z3Q9XyA==,type:str]
kind: ENC[AES256_GCM,data:eBVmEiFA,iv:ocfaseG89H6s1IrCFZJ8p+Yp+e2Ho2I3LWIHW+Blzvc=,tag:g1MywkPcHhbsfogE3XBWsQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gIZJn4XPvHeONa53cTDvePrMKg==,iv:b7GwuRyzfcsV32SbOQVC3RISw0Bxxn6/FrQNAbTO+vQ=,tag:mveFYO38LgRRPlsHQnhl4g==,type:str]
    namespace: ENC[AES256_GCM,data:C/hbV6mIky535w==,iv:JYx+JBsSliQvh0djNivpxW2zY2gEocDmn+6kizpK7SQ=,tag:sXzluvxKOKHymrEMSu2ukg==,type:str]
type: ENC[AES256_GCM,data:dU9IX9Uz,iv:0Z2lpvI1waDL/zd5JMwJDa4H809AcKTfbrs2p0jBf5c=,tag:cbsg54/2G34Iwt4djDg9xA==,type:str]
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:Z2I7Z+gktfZ3LIMixQIjIw18vpofhKxKnCHxN729s79wrIJF3ZEe+N/F9YVM2R4Jvi+/W/nZYvmvkOiqTEhV5brF1i+ynHTzFjNxmqNBXN9Y+xRMwz8qWCn9t9paEVbwocRwzBl+YPALVsXuNWvf2gIWwMPINd3kRioerWoyt0sWasGxW4yOnoI9aBjo3vskLzYM91AEzC3lnR7ADtjGZZyiIRfmHZsCF3nCafSXafrKg3ov0c3QF+J/QEP0aN1eFUsY9wgPbjGZsQvtRmgLpKZlir//Gdx7ahNrvzY84xh3e0xUf/Er6YR9ynYehqWGrsROu0yFPoNcLE8WxWM6sOZgmo3ZnHglpuzJKTlOZ8559zBpLiocTQlJT5jnYE+Q5ebZUoyN3Jksg3hJqltZ8MqiyGMUNk9efAc3D1z8qVX5ka+O6PnOR1SykNtNy48aZ8x8DVS7Kzi49pbMF6sGNOJnkgsZj1xGQjXwiCEXOv9wMd/k+Ffx59Qer5XcPgF3VQqiLrWZlSqAc8eUPsnnbWckpi2V9IFIhI0V1VZispKMrbQSNBNrlfTT7PNsTztt8+MZ0++9ofLHfztsGVK2J6V+ygrisjNbwc8RHPytHoeiZq1J6+Gsl4ziHmks4l9QZOgRz04WnVbZNcz3cFz42QXPB0FYx5BIHiVfLXA7pnWYatJRkAMs9ThwD+7RNVwi44VfO4pLOO80VGnFrkhYnjLWImxNoHs/343gIuau6Cts0yFO+24ZHDYg+tnxQYPCsqnB+4VMTIa/UFIQmaSGfOFFYXNUA69B31A4dSEZzx6va125GKJX5a4rdnqZden1QeoXcHTMl0eqDoP37xt1xRRBk3W5uaWrB8ZRpeDgtaqCvgH7T6EUvFHc2+ViJUqwphUWXC49iAdFF2isXcs1AfzdrQ/J,iv:JtN0lOtz3KYTomH/qoFj+cPW0vlECdDTXGxrld3ZUeA=,tag:BzBVKRSnolhYEyNVbVaTNQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5azhudlYyVllyTHBwTkV4
            QjV3V1FVUGlVWEVUTmszTGt5R1ZBSGpUTERzCjlRVlNObXRiRW5MMnY1NWxOYWJK
            TXNGdEx4bVAyRUlCZTlGUEVqTWpDVWMKLS0tIHdCQ3hpQmtSODRIRXIzaGdZdm81
            elRydXQ2NVloM3pHZytWdDhCWTFyZ2sK9gnajK3XyPkoiQLTEMeXBB89yRYI8QMM
            zTQ6YgSaLcOgaogMKznDZVmiOvMNbXyJerl9NijE0f1BxpVYpottAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pht0t0fr9gr8tf2vqm5y4s8lrg6g2xtql5m2xgzm4lv38mhaqfsslekwsa
    lastmodified: "2026-05-24T21:02:54Z"
    mac: ENC[AES256_GCM,data:0aWjnmZPR/5o2bBAFR+hR+v6wMzYC2YpfA0z8pct6xQNWuPZETfRXRwhsQKKNPsXUPL0fMTrsXtDHJA3xaXB5uXxpznhoGvX9GGtOzu4EiBlkpgfMbJiluZKuSnQl2Zusji7Nqux52Q1RAX34Ty2ID5TLqlLIZML9nn0SjL6a5M=,iv:gCylnmzOMgyocHEwzLeHXQAb1g0e8IoKLMs6u2LFdPI=,tag:ps06V9vCRVEw+kyHwXmjMA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
