apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: monitoring-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - monitoring-secrets.sops.yaml
  - alertmanager-config.sops.yaml
