apiVersion: ENC[AES256_GCM,data:bxw=,iv:zwUuuFAFHmn9NFoqMubTuG72OtTKbUG5u7T+WDN2oW0=,tag:1LCGNmy0pBnAEBBz3VeXiQ==,type:str]
kind: ENC[AES256_GCM,data:ZQ3Hkaua,iv:gYPhZSfjbcpyUvLV1HJEFj0GpGUPnSsdmHIbkSDhQ6Y=,tag:pD6qJYQ0GFIU9Cr4H7zVOg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NDMbX1NggVTFhY7KRGcYRpHR,iv:q7CYA86GazCN6Vo7/1tQXpZWLtn2uGzkKDpfBRtTZxE=,tag:BKNkUdtYV6I50mMOPrKwVQ==,type:str]
    namespace: ENC[AES256_GCM,data:H31PHZz0dvmJfQ==,iv:dKADdp4qAsm+TDAjp71Y6+ZymftXmDoXCcG95AR3EfU=,tag:h8fJlcL7mbAa/EPa87LxxQ==,type:str]
type: ENC[AES256_GCM,data:dVzQep+p,iv:oXLKu8EKbGJBn9/QIRYa2yb/PLCOe1xwwdQEQzEU/A4=,tag:axbRlMkWMLiD3nQd8ZQ+Fw==,type:str]
stringData:
    grafana-admin-user: ENC[AES256_GCM,data:Kz6F8OA=,iv:jF8TObFJviEjFAugL78NXhf1/uVCKevDmZu0AnBiKwI=,tag:50yOXIOCbRkE/GwVHWKMuQ==,type:str]
    grafana-admin-password: ENC[AES256_GCM,data:grK1tEBsy5zdV1sZ457TK+2YDHjZ4xqwOcQ5B5rUOtE=,iv:1b1h0kngAEML0sn8CSCT7HA5CofBUlju1JFNR25Xl6A=,tag:OqONdRyPe1YUfzFqGm6F/A==,type:str]
sops:
    age:
        - recipient: age1pht0t0fr9gr8tf2vqm5y4s8lrg6g2xtql5m2xgzm4lv38mhaqfsslekwsa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VnoyLytVQlNlSzhBRmVi
            TlltNjlkUVk3VmVTRDdwMWZ4TVNybkZyWlNZCmhMdWxpK2dDaE1YZWVQNytTR0ds
            ZU1sQ2pyYWx1TjNsbEdueGFIRVlBZmsKLS0tIFprVDBpVW1sbzJQMzM1WE1TNjhB
            L2QzOVg2NEExNEx1OGMwdmR1Qk9OSFUKIzq0Ero3WL9JKVlydZSWKjvWxbuPSNjg
            kJOlF9U/fCTWCxqiJWBXA+ed29X6AU1DiWZH4VZbTWupxvE69wV3ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T03:54:57Z"
    mac: ENC[AES256_GCM,data:aDYWMT1ytnud/M50d4yZcvKWTgIjTKyy+EcH6RpwNb2zHxJVwmhosaK6kgiZURMP3SayRZ1pOtRJiyUXToI2hGO8i4f5LjdHiHEbyyV921y0Nts+uLql9oZDN6/MxFK8w07MAtUELUJTPFIzqJFUEqg6dIUfDTCKoytMrr2QTU0=,iv:pROq78JcsOnmVx26OlR4GEHl/KfJS4qwlqc2wgKYW48=,tag:Xtzj2zen5qcfTUsQ0lU7Vw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
