apiVersion: ENC[AES256_GCM,data:b2Q=,iv:N2fUPYCcnqXB5EDYk0jQMOF1pICGYJsD8MLTRo7YeDc=,tag:uszjiYUWqskp4wWYmXXGgg==,type:str]
kind: ENC[AES256_GCM,data:rFLIAWzq,iv:RCNd5lt7cHwyltXvWpMuAlC5K7AJp5ukCx+PGyc/WYs=,tag:S/AMYf+ZEtolDg1XYxEHHQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nbH5/qqT9ERh4PIPfHLUmQ4S,iv:+sHLfaw/xNoYJmbE8SGrItahxwYWmDJWJR8dFQ4khp8=,tag:Tx6dASXGFFg9HmsRI+dF3Q==,type:str]
    namespace: ENC[AES256_GCM,data:xv8ovvow3WVQww==,iv:BWaI/P5Z/gwTslPoBgxYeHYlo6jye+/MJPs0XLfFkmM=,tag:a8u9t6nAxpSJS1GdfyTDxQ==,type:str]
type: ENC[AES256_GCM,data:ChrItUol,iv:XqS/oaOWyi2JGjvSmFozkfSjDo2FU5kYK+o2LsjJp+U=,tag:/TlOs8RlbPk0t68KImrkuQ==,type:str]
stringData:
    grafana-admin-password: ENC[AES256_GCM,data:2yjjBkZrYV4WxVmYKvuw/kUC3zeeZBqzqH4YOXBGYeo=,iv:4INIIx/jdgnwX3LEqFjgRIE3elP1nf5AQY38szBAh6E=,tag:LHbTn5FB5uA+MgGpTLxCFg==,type:str]
sops:
    age:
        - recipient: age1pht0t0fr9gr8tf2vqm5y4s8lrg6g2xtql5m2xgzm4lv38mhaqfsslekwsa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDVFL0xCWjRDb21ZcHRr
            K2w5cWZzdXR0VDRiNklUWXNReXZlUVVFZ0gwCnozcVk3MmJrc25nZGtVRDBsQjFK
            NWFSV0NQeEh2bEJhejdTeWxydmxHcDgKLS0tIHVrQmgzWkRwNjVERGUxTEFobGpQ
            TWxVU1NHUGY3QWhQNENXNkg4Q2dOSFUKcXAPgRhmvIRlh+jNOxK7fgljWRj0p0a4
            k2no1MZEZ+60mY+ymuoz4ZUM2NP0EZOX+yEXYC0cKtFk8jBqLaspTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T02:25:55Z"
    mac: ENC[AES256_GCM,data:g31n6mV97ud+iNGJI79uWl2A9ElMHeqXu22d7gQY6B2Zr03aNIwrQuq/1HK1bp9Qytp+sWkaVrbGoxr2y8kPIyPk1qDKOnkiSLIkRVP3N5+hkkbKAA/5in0OYP1OHoV9EpB6ZMOd5xd3vleLcjXllKzyeqXZEBN9hnpBGkCeyvs=,iv:rwJHIEOn9FfJl2GMb8wnJ/EoVWRSKadRdCHrdRRmU84=,tag:tL+pw3XE+HZ9HaD224JMIA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
