apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dash
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "19"
    argocd-image-updater.argoproj.io/image-list: dash=ghcr.io/ryyyyan-taylor/homelab-dash:latest
    argocd-image-updater.argoproj.io/dash.update-strategy: digest
    argocd-image-updater.argoproj.io/dash.pull-secret: pullsecret:argocd/ghcr-credentials
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/ghcr-credentials
    argocd-image-updater.argoproj.io/git-branch: main
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ryyyyan-taylor/homelab.git
    targetRevision: HEAD
    path: kubernetes/apps/platform/dash
  destination:
    server: https://kubernetes.default.svc
    namespace: dash
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
