apiVersion: v1
kind: ServiceAccount
metadata:
  name: dash
  namespace: dash
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dash
rules:
  - apiGroups: [""]
    resources: [nodes, pods]
    verbs: [get, list]
  - apiGroups: [apps]
    resources: [deployments]
    verbs: [get, list]
  - apiGroups: [metrics.k8s.io]
    resources: [nodes]
    verbs: [get, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dash
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dash
subjects:
  - kind: ServiceAccount
    name: dash
    namespace: dash
