apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy-config
  namespace: ntfy
data:
  server.yml: |
    base-url: https://ntfy.lab.ryantaylor.tech
    listen-http: :80
    behind-proxy: true
    cache-file: /var/lib/ntfy/cache.db
    cache-duration: 24h
    auth-file: /var/lib/ntfy/auth.db
    auth-default-access: deny-all
    attachment-cache-dir: /var/lib/ntfy/attachments
    attachment-total-size-limit: 5G
    attachment-file-size-limit: 15M
