apiVersion: ENC[AES256_GCM,data:ROA=,iv:gS+mgdxTsK8RDQ2kuwMnOXS6uR1eUgk+RMY075ACLBU=,tag:r58tZcIICRxul2M0rLj39Q==,type:str]
kind: ENC[AES256_GCM,data:IDNiJEKy,iv:C/9vW8nZ5cjqEb90sLQEN9YGrS5tqynofZqMeB8Ijy8=,tag:/KsC15eAtsC60umO+TVx5A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Bz9RYtPGKj8iGdqp,iv:RXyU4GTrgwjrPPwcjnvYX/R8KaPXZMq56G2NDSFA4SQ=,tag:/0z//udsOckQZO/LOHgnAg==,type:str]
    namespace: ENC[AES256_GCM,data:ZANX1w==,iv:RaBoetWyhu9yjxJXT0ki5FawW4lAWtNVCTl1mCNtdDA=,tag:MLkFU7LnJSRTgdNwNrqVhw==,type:str]
type: ENC[AES256_GCM,data:2xLKgUYA,iv:mMycu8ecR5uBwm8N+XjWCm1LYd1kN4p8nDNGGrXKfVw=,tag:79fj3LcX497gvAjO7TSArg==,type:str]
stringData:
    alertmanager-token: ENC[AES256_GCM,data:NOmsFqL86DZThqx+BnZB7kC9LKVT7YWDeejZaCwbu9Y=,iv:zsp1cOvV3gCUb3dJgitDKmRjEYQ1a9jzNaXpHfr77SY=,tag:t7px12odWvkRm+5vi3Aa7Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVHVya3BmWHc1bGwxeU9M
            M1JkRCs3NkxJakIyaS9YK1VBVUNua01zWUJZCkZsZ0RtRVNyWCtucmVlN3k0WGlw
            THV4UmRRRWkva0g5U1VqSHR1Qi9KMjQKLS0tIEUrNExKdHUydTVvajhERWxkSVFI
            dmcyckloMExZd3FQUy9JcHNCWC90M0EK1FdtuArjPD5IlnegP0qeV2xDtfqnvLfc
            sgX81bTrrbTKfZ1iZEaEwZ5k8JZszoyxS6y/X46ttel0wRpc+JjsYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pht0t0fr9gr8tf2vqm5y4s8lrg6g2xtql5m2xgzm4lv38mhaqfsslekwsa
    lastmodified: "2026-05-24T21:00:19Z"
    mac: ENC[AES256_GCM,data:u/jlhxTAmcRF9aiB6xXUs8Pd32m5Mybcp35snrjZRqbKpFHICP91XmxupB2VlgJLB7MKHX1P9kj75B9NIpUnYeIRC+VHHy6u85NjJfsOJvtVMOdA2ZKfLycfDTWmZfiT+oy4l8ywcAypktV7oQE/E7JOii+f/7yZYBeZAsed8jQ=,iv:3yr9riU09krMtlSPMHfgt8U5a8RXF0bVcrambJdH0Sc=,tag:u7RfwhHPC53kWv7tOlqcRg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
