apiVersion: ENC[AES256_GCM,data:uCM=,iv:cAUc/49hWvhIfZz9frg0/r3iuAYUwIalv+2VxW227es=,tag:CsYgCz7Iai6BzBTuK+bmQw==,type:str]
kind: ENC[AES256_GCM,data:3AD8KvjO,iv:r9N/rOxVlfQthUxQLID4uvqHC1LWZLDduADstIoGdzY=,tag:XWZJIhdEAIKUxGHUuDVGZw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LgjHgKrXHMM3Efnt,iv:KPtG8K92tItGlXpM/fVj5BMeIb596A+xvpjLKa7F40I=,tag:6rjAoY/BdbGvM5XOx976Og==,type:str]
    namespace: ENC[AES256_GCM,data:hHN0xQ==,iv:TcMo2F9rIGnFiFWHFQOBuqNW1IAoO+dWPhEaMl2gqGA=,tag:rKHtrL8lZb4qrzdIhCESOg==,type:str]
type: ENC[AES256_GCM,data:MThstVVT,iv:PWUk1F0sAiN+Q83wICfKHJdSqNjAKS+w4vjD53Vwtxg=,tag:no1cPldTwqpb+K6OGt94JQ==,type:str]
stringData:
    alertmanager-token: ENC[AES256_GCM,data:qMjOj93uZ9y18ppkt5LdEcj2GcYzxSSpKUadJ63Myxg=,iv:DBUT8jH5x+qFGHzXaTVLj0Phk8qes8f4V1khy0yvirU=,tag:LhcToBgVrsDvSzWlZxQDTg==,type:str]
sops:
    age:
        - recipient: age1pht0t0fr9gr8tf2vqm5y4s8lrg6g2xtql5m2xgzm4lv38mhaqfsslekwsa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RkY0bnh6STdwcWlSbmJ4
            NGsrYUxFSnBLQzNTZFdHUDJRS1BOVUdpcjA4CnBQV2xYc2RCSGc0TlpQckR3ZmVC
            dHNhbURsOXV3ajRFVDZKQWFrY1ZnbzAKLS0tIG1reUtKQmladU9FNitaK0lMQk5r
            STdPSFN1dkdwSVAvT1piU2YrWGNJakEKDPjup+5/3D9IxxsjT10SgK1uXipcpuTW
            TQ5AmG5IQ/PjnXyZEiAupYYCXMoD9OcaQWqPxRJjhVTtaAfKrkPusg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T02:19:35Z"
    mac: ENC[AES256_GCM,data:CIgRv4DRATM9ebuSodsOOOAq+Vi4Vu34VTrN3w+Poh9OvScw/Rq9QKSv5OOm4NIythj9eZTFtfAzkC/DFWt65euY1SzVg+aeKMHuiJHrCDZox1MGWTyGF/I3h55Ax8aHG+FpfquZrfxIKhT3KUCC1sJ3wG0hvVjiixb0QzT6AJo=,iv:A4QOViLsK86SLFLRheRBKJ+I3j85IACQEgS6zVn133U=,tag:dAY4Uc7ndEBnmo8qD3bMrA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
