apiVersion: ENC[AES256_GCM,data:OFk=,iv:/FoULD7sImFS4Gg6DvHdSsHjSv8AjWBGxmLY/JtOLN8=,tag:fwVB0ZktVA9q7X07hte8kQ==,type:str]
kind: ENC[AES256_GCM,data:FVVUeqW8,iv:3AYV6mD7NgR1fE9csmQDlNrSdDwWSKTbpJAmr+zGz4A=,tag:NYo08jFQOd+9QEgnwQS+kw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7Bck0ATmyjC7awGA,iv:XzgvPCZ8GGdJ536DLyu18+zg/v3iCEtYyU62hS3hl8o=,tag:w4nnrfF0UYBjbZE/jPPIBg==,type:str]
    namespace: ENC[AES256_GCM,data:mxJDoQ==,iv:wX7EJ2O/Ip96h1eEsR23dXaPRLg0Kl2+JPEUtXbjdRI=,tag:qZ0crsngc2Rxbi7tncWPzA==,type:str]
type: ENC[AES256_GCM,data:EGAngR+v,iv:tN9jReonnGqwEiVkpPtMRW+8+HU80zJXf2yJClHR9cA=,tag:5nHuCdlrb2Oi2kb033Lnmg==,type:str]
stringData:
    token: ENC[AES256_GCM,data:RowEpNVyLXkJe+BSihpxPZBJZN4y7T3jspMl44ao7JXVgnKHXaOzcA7wXqWD603lDbix8KiPRw==,iv:83bT1lP6JnjMS8Gp2g7+ouOSiNk8+qqHyOfkSmheq2Q=,tag:lcXoAai5c2/kQ8bAtIC1yg==,type:str]
sops:
    age:
        - recipient: age1pht0t0fr9gr8tf2vqm5y4s8lrg6g2xtql5m2xgzm4lv38mhaqfsslekwsa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Q0c1cGNoTE1DYm5Pdk5L
            NTJDdmNWLzVCQUwxVXh1VzRPeHpxTU9rTmtNCng1bFZLd09IclYrc3FCejZkL2sw
            b08wK0ZRUENRWk0wWU80eEF4QjEwVEkKLS0tIC9sanFCRkxzTU0yRndrZGJDUk1N
            Qk96djZoMUkvdnlIU2FJaVhrZDA2YWsKsNxdZN/1SoiCPYAnmB2OUg0fetMAgeEq
            leCVRx2hahyVKB1vVsT0hXS11zusmVE9o9zcRVNz3F89xL0FK9gDpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T05:41:21Z"
    mac: ENC[AES256_GCM,data:lqADhW10IOeI+F1muwtOQW+woqvNTeOOSepzuq5ILi+cFO7xfPY2zubYSvjJ3RwqYLvkIE2zLa9zwfoVepZlm8Yq8BoKrY2+LJM1FPuUkP4+bFg2qYUtEaTPbkYyg34xrw/N42dXe/DNGJY163tQJodo7U6NwtZY/JuLTiNO7aM=,iv:K2wfXQJTEcDgSNOjlAkOWF+VKn3cgwIJ6MbduZzPTfc=,tag:xp4VMRtTdFKtVLqGUGTJzA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
