apiVersion: ENC[AES256_GCM,data:jWk=,iv:k0m8NOgejXE6BCZmaJ6OvFboaRETVgTQ5flnDhFmIrk=,tag:h/Ayjirp24jIbwdpv7Omvw==,type:str]
kind: ENC[AES256_GCM,data:oWrP6rxU,iv:6zHfABxTF14Zvp7niFemb6YX3wi85s8eCXXQ4d9nHJM=,tag:p7uQoXP0mXWI93zvrdCfqA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3aCL0MCBi/MRf0j9ntY=,iv:TAHOw7PBnttOTriiiipx9y+pdyZICP7vKYZRATU4kwQ=,tag:zxuvhpVohHQe+gCA4yw5lg==,type:str]
    namespace: ENC[AES256_GCM,data:xFaAFA==,iv:sZeZ8IIbCb56kYT72OBH6qWnaiXIL1aOOl99e8fAG/Y=,tag:WGejEMpqMlmmXrQbwS11Yw==,type:str]
type: ENC[AES256_GCM,data:y97ci78J,iv:bsmprL+aVxHYjgyOov8xGKD7eGopdTcTfdIT2qpzK4w=,tag:mTraI+uElhO+QZy51NchLA==,type:str]
stringData:
    token: ENC[AES256_GCM,data:5fl3rwyC2+c0Cr8jiQQYcqm6NV2VNQA0z7imQPkV1frQ+XK5w0DfzZcmZuU=,iv:F2pL/Qn6t0EGyFgX7eY8Ya015TWGTbUonpNKAZDQLRc=,tag:AR7sWWiA+4eUacSudNCnGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aE5PeGhrUFpiVUVyUWZU
            dmQ5bHhHUDA3L2xtakFtY2tqaFZ0eWNMZzB3CkxwdE9sNm1BdHhZb3VnUXRkMFBQ
            Z3krVlRVSEpIREFwck14cG5GNGVmSG8KLS0tIDh3T2Y1L3VWZjhibTRRdlNGaTRL
            SjFTMzd5bFpWemV0ZnljSjJONlhjSG8KUtHh1PDV++2H39sUsLJni1iDxghdLaXo
            bmiIko2Wj6Vr/2ByNnTRjNN4W/7LO1XwPhooGQ1V6+gnON/GhzMlyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pht0t0fr9gr8tf2vqm5y4s8lrg6g2xtql5m2xgzm4lv38mhaqfsslekwsa
    lastmodified: "2026-05-27T18:45:29Z"
    mac: ENC[AES256_GCM,data:m5UwwEEe4Ns2C5ro6D9jfEepOLOoX/nCDQ9cjikOsUN9wOLuPJIvXDMvHOaZnMCYL4D50JXaW5Xzi+oxBocY2rVvPW0DR43J/zfgesFlGk6WOaEanOiTJXdXg13YCN9aOpAcIzcCus8PrciOp0aox3DoPh4arl2WFmfpNxoZEoY=,iv:B+wM/hOV/VCu5TkmjFb1MXh8cVYR8Kil0Xp97+aF0LY=,tag:cu+TI86Gw6mfVsjGooOReg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
