#ENC[AES256_GCM,data:aLpUq/dfzKfW96/TUC0ICEMnIV1eXyrGDADzRE/3t4YvvyE20Fx6wRLcnsfAVgz501uttdnmfw==,iv:QeywrFxnP+OwNUkoXkVHdfMzeSJaYIMdh/RnbpJmzS0=,tag:cxY10Hr4yy9BoD5A8fqH5A==,type:comment]
#ENC[AES256_GCM,data:AcncYPPBj54yk5xLxaRX6Pq243RW9nuvRylSP1j6+RnjXQHYP3aF+WJVZq2r1A+/CK95HZyqOAN/1Ss=,iv:bXeCc4hw1T7t7C2MMWZygPYJxsNQyBzoi35UlNYzUy0=,tag:NRJ3p0+gPJh5luKlxk5jzg==,type:comment]
#ENC[AES256_GCM,data:K0dSBfys7l7qD52ikfnqQR/d4d6giRFDDI9dZ71aQqQwcb8aqmC1tHgJ52O/p8Kyj9hWZ4YtVdM=,iv:9+SR7K9jrGKSCYlhCVN+gPhzfGcI3vStOGq+Kwm/QRw=,tag:1UcWIMcfg291oknwgVPv1A==,type:comment]
#ENC[AES256_GCM,data:F0zmFu0U3HbxGA==,iv:mNs7TH+iDajYhZPCA2wgEpau3mhasZhq7mqc4tv4zRU=,tag:ACF65W4U5LfF4tjmKveudg==,type:comment]
mc_rcon_password: ENC[AES256_GCM,data:Pu7J7Zms9Fuo3wilG5FV,iv:7pWhvJgL1LpU8dvWy8UEo6VegF/9EnD1nCr4sk/UaE4=,tag:XFTsOu8BxnBcnAZ80ym3zw==,type:str]
mc_management_server_secret: ENC[AES256_GCM,data:Zk7fhbwRMWAcDB/SC/npzN1ft0M3LwFOeQAgXfWmn/gKTjZJeMgAyQ==,iv:uzUDLdr7h159lYvQPuNCTV+OtadXEvdag6Fw3y3AK7k=,tag:VyIbxLPjFbiobcM0aF6iJg==,type:str]
#ENC[AES256_GCM,data:+DZBzfiuam+u,iv:FgMzxp7TuLbwkVN/xm3VlvcfBcJRVYwrC6EIkHp/aeE=,tag:6VatehpfJ8Pi5BFkDsLymQ==,type:comment]
terraria_password: ENC[AES256_GCM,data:yjjd,iv:S2Mia6CkTWzxic12MLf2THaAv8t7G/RicBQeBKNVhcI=,tag:yYewpBPPg/v6EuOHD3WHDA==,type:str]
lgsm_steam_user: ENC[AES256_GCM,data:TVWcp84j5yMUYGc=,iv:Jly8+HEP6EhKWgeWuWHGBRlGzq96xXBYZNGoTUSfzhc=,tag:h62O5oWcNfzWU1RbFYjUNw==,type:str]
lgsm_steam_pass: ENC[AES256_GCM,data:BUypNjbnMjCS,iv:Q7MEObHTxTLgmQwnBms/QZzp8FhOzBaDMmSSFVLplxM=,tag:KYTAa5i5OOOr5OsH/NzD6g==,type:str]
#ENC[AES256_GCM,data:3BJIUwhLX+x1bJ8=,iv:HjIK2IUXyVlgUl8S3E3BzI8+q9nR6wKHsZrv7NMwkSc=,tag:8G3BJOT3HeDwVpohXCRe5w==,type:comment]
ck_password: ENC[AES256_GCM,data:7lr1,iv:d0Iss0SG71GYanlB0PaMjvmdjEYUSHh8uzsduSYTVWs=,tag:GKThc4jLmGQlYJkNpy2v2Q==,type:str]
sops:
    age:
        - recipient: age1pht0t0fr9gr8tf2vqm5y4s8lrg6g2xtql5m2xgzm4lv38mhaqfsslekwsa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTDJrbUNKMGVqREdDWU9W
            SmpMcjljdEdlOFd3RkxVbm9qNlF5Y2ZlU3o4CnBBUWxnYlZ2Ymp4YkROUFZaTGp4
            ZkZFRHBycnpYM21xVk9pUFV6bmVSVlEKLS0tIEliakVWaGVoOHBTeEZyWHY0Y3Bl
            V053Q2UwaGNyaVdDV2RRZGo2SThwTDQKybgGypLihqi3JWnhQCMXlaUPVvSX9KIu
            6+Iz79wBu4un3ooW9NvEhl+z02cu7I9FDS6weVaCpON0z2xeLNbo2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T17:00:50Z"
    mac: ENC[AES256_GCM,data:lPwLw6u51BPPNpGRJmKUX5GfJPj/e0FUjlPu2PlvJJ9HlpILscWQGnpQZu4f/2pK3xvRJLrBRwqyPHo91v4vxJ/mxF1AjallruCYmrqip5GotKIRvV6CJRWfVWiVrHaSl8qxHU+Cu7fQY/R2uxhqZeA2pBjMCH++4OreJlixU3Y=,iv:+AcRJNo2gtNM9bQ7IfXvkPvFHY+5yrStRBWpbSSxBfE=,tag:oEEJut+CClG5QkTzedBJ+Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
