apiVersion: ENC[AES256_GCM,data:10Q=,iv:iwDy0UITc7qA/D2smAv+gyvrGF6u5VaMSnJiv34S7g0=,tag:X6dtnzMtgCmU2pytXXAsMg==,type:str]
kind: ENC[AES256_GCM,data:nQUliqsg,iv:R82uKeUwsuj64SuqMghQ0ZpD16/ADSTUp9ZdfWT7I9A=,tag:GyJcWaGK7jsZRanmZLB2Tw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4QfFG0seHi/6xp94PyD9QL3WmQ==,iv:iOybke/gJc4fKfTXDUiy411HSaBmteIthx9ZykmfsP4=,tag:XBbXM8zzqIb42axheoCPig==,type:str]
    namespace: ENC[AES256_GCM,data:PHowUPhVhoVE/A==,iv:1om3uOQHyfuOnIq8ZfP2X9RL55nLl9DTUGmyTYucDtg=,tag:zeMhgwWRstRFV6+F8iTyqg==,type:str]
stringData:
    url: ENC[AES256_GCM,data:7258DiXPryzL4ntqIvTBIyiNYDduavPzD1J1qgQPUNve2WOHbAZjM6YZWsJj+y8=,iv:veb2cUf3sWodNWkQH+MJFCtIxsTiJ8uwIFvHgzyC4Uw=,tag:3HzdXfxWcJKEjYBTL5ATjw==,type:str]
    token: ENC[AES256_GCM,data:1U57xU57jbFDNnkJYs7X8T4eBra1eO3zhp85GNt1bUU=,iv:Mx2O8U79BqmkJWumWdBGNgxiK+1oSPoq1Zf91F//qG4=,tag:iJ5Bzj/mq1OAdvipR30Fuw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWkVJVTlIRit4WmxYT0xU
            UnhWdGZRSkpiS1o1dGNoSmZsOHVsR2xvZVRVCnEvTEZIcGcwSW13ZTBRVjRvYzk5
            TzF0K0lLQlU5RS80UmswZDRpUEtpbzgKLS0tIDE5UHN6eWpSQlRFbEtCWC8yZjA2
            SXhMYyt4R3pnQnF1TzJFMmNYdDJKVUkKlT77XWl3KAlLGp2sLSp4aqz89Fa5tsrq
            2rK6EJMHJGdVYp8MS5PIeNu63a152U7eLB4rtUbsGapHC12PiGZolA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pht0t0fr9gr8tf2vqm5y4s8lrg6g2xtql5m2xgzm4lv38mhaqfsslekwsa
    lastmodified: "2026-05-14T21:04:14Z"
    mac: ENC[AES256_GCM,data:ayk0z8gr53m1oGCTiMeb+cVmMMAHlHvpS2UOlma0ze6LEru08s3ugpdM2IFBgEUAV448Olfs5a1MAKO5z9vqmeSUDL1YFUdFKwwDEMncfm+CNYH3HIFUTbhxYqL7rafWOrmizocPDwpWJvxr1+JtZxEyEX8u6wWJdbT8pWgOfQw=,iv:zeu/In1ToxwrBhqQ8s9a8BHdy0dR5sWqPjj/aSvpSLI=,tag:7aVaGbFGa3THLVBnqfM6bw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
