apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: cluster-health-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - cluster-health-secrets.sops.yaml
