apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: semaphore
  namespace: semaphore
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`semaphore.lab.ryantaylor.tech`)
      kind: Rule
      services:
        - name: semaphore
          port: 3000
  tls: {}
