apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: semaphore-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - semaphore-secrets.sops.yaml
  - semaphore-general.sops.yaml
