apiVersion: ENC[AES256_GCM,data:vjU=,iv:OeFQy8xK4/GN2rdnbyslJZC2rZ2bXOZ/iG423NCYC+M=,tag:wuXvdRKzMdLF58DUTRTxKg==,type:str]
kind: ENC[AES256_GCM,data:P/jrZeWA,iv:C4tF3RHgPAi1NEgXozsLiOPZCQ0Xmuej88GJ/RlaJ1M=,tag:kxzO6f+J7HBIL0kRRhaRLA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:YfenMh2gAJd6SCxQPI5aKCg=,iv:K1x4SSnZRfCfoQ6Pyl2WqDzg74Usqp6mlx7Flxkj4F0=,tag:GKtYvEBJZ6458t2d2jVyrg==,type:str]
    namespace: ENC[AES256_GCM,data:VOrkEtb2C2U/,iv:OCB19aYrdxgNKmSdXokAqqOJvNzzkdwuG1swFfrZFCY=,tag:EIzNmaG8NXdEv+5kCZrICw==,type:str]
type: ENC[AES256_GCM,data:/9beIzPM,iv:xPVX2FbRhOYwQ6d6MJolPfUCaeH6BhRX++/dpr463b4=,tag:DLwhRRAwdcGK7bkEzEmAJg==,type:str]
stringData:
    admin-username: ENC[AES256_GCM,data:CNaWsGupZJKh6Zut/arI,iv:Kx9v3EE1zj9nI8Zc74VtFTnh0XE7Fa6aGLoaQfvP/a4=,tag:b03XfOlMRwGoF8pImCGEUA==,type:str]
    admin-password: ENC[AES256_GCM,data:hi5/aC5ywmxvct3gtvEt,iv:t1rV/hEICLSfqUyhlFWICamnK1iKWIwdOMoh8tlosPk=,tag:/+64mGQ5N3Ite4L+Hy+v9w==,type:str]
    admin-email: ENC[AES256_GCM,data:2QS5Z579ofwjZMRjy5tVvgq0NaOYtccN,iv:Mrz37r0WOIabPjhuPsNMu1R9GMLUoquwg+Zh4gxgeoA=,tag:EsQ0s4r9KpQDI5Oa1l1HjA==,type:str]
    admin-fullname: ENC[AES256_GCM,data:SQ8AU6PlPIdbaiiQInr4,iv:p+2/7i1YZssFDj+/9heZvrDpZjRV4HJeW54SOi8n3Ho=,tag:W1z1AwlmM36CwkWNe+EVPA==,type:str]
    oidc-providers: ENC[AES256_GCM,data:Ke4pvvGgn4VzNHlCLwvtltT2+iSQ3Wpat4NYgJN0r0pmhrqSJybqn+A4XLS4xgs8S3CFwY4p/M+qJENIIuFmKGqmu24m7k3BzPYNFogGyaDVvJHMvdQGIEl6Nfo76YF6poqaKQnKpQzJXnr/hAJjiuqu6amRTCu9irgkez9De3X/2eF3DmEsWLwgrKb+DMsRi1ApE3FBRxsu+GtfOt6DNBK+KAiD5n7eXbXjW2e/0DV65Q4EXGohX58clP58AKSAyEMZBR0QWyE2t2uhnxyZjZARDJToAdr0ZApXrVAwdA5FpZjP+DhMvk7KK6sRpoJeVhGH/+x86oIBhxi/+ibkYn9zYHwgZ/0YOFI9s/egAQNQF497pwXde/NKcI7VDGyDE99KJxMkVdK+bvluUqoJ9ZUIbXNThiueNfO09ftMjeP8xcUteJq2iRef/SP2SRpXlikVgiO3Et4nPc1hQWdNuDxYbppsORNKmi/VpvfqKtlfcDGTgyqgNSYcaH3rSgXK2my2KJH/c6vXiW5FOWTVWzUfHvxwp8FPNcImiB7nYMaMxUm6wY7NQb2a9D++Bm8wVB7aTeQzeH2XJSf9QlYsgOGQmSoil20DhCD44ebzYabOeXLU0Sv+2qTIgKyHjhDiJKD6McC3aRLC6oqqvQp0pC2yoVg5bik2rOy/8sisfaGq4H8YR6cAO2jMza+vyd864Ph/FDJiLbU=,iv:DNlQvGqESiK+0H3eFmZFGBpwprqXoEgpZLJWfavQpDo=,tag:iqNjTUqW75HcTvO7GYRPOA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUR2QrZ0srbWNjcFVFenBa
            VEFCUlZLbXlqakJsTGwyVGhUanVMdWFWOUUwCmFDc0Jybk9TenE5eWJJdkY0Nzl0
            WUczZlBpMEpVMXI2SVZZL0hQb2locEEKLS0tIDVrS1UvelZnLy9qVHVXWm9Lc3U5
            dmptV2htN2lVa2ZlSmlQZHNGVERQeHMK15qTd6wHq2iqD49n1hLSTt1a2Ic0b/2x
            KpUayp1tLImrNPEMjYcNE7ErWP2HSAefOomdZWmktcH7Cv8FtlK5fA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pht0t0fr9gr8tf2vqm5y4s8lrg6g2xtql5m2xgzm4lv38mhaqfsslekwsa
    lastmodified: "2026-05-27T15:38:23Z"
    mac: ENC[AES256_GCM,data:M5ju73Osb1zHUQVgnzzkz2mNdz6ycqSBkQS/hexqUsKooLq52VCrqb2820UJBILDXT3VBwJNO8J75efgIuzCpOx4s9hLhZwrkeF07dqD/i5LHr+L4I6vwGKMn+E7RJ0WPUGVziE620AaNNEAgBQfjpE4wLraqnxm2muUebgX9/8=,iv:ZQqF1jTv47uakf48+z0QnaM7ZhYeUX0I7QG4G1lk8T8=,tag:ADkOOBpk/hP8YuuGH3xsfw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
