apiVersion: ENC[AES256_GCM,data:tn8=,iv:Nz92rAYlqcqupBllfsLbNJTKA9NoimGNLzAxSUivSJM=,tag:osCsOKzKxCnfj/Do8t/S0w==,type:str]
kind: ENC[AES256_GCM,data:SX0DUsKV,iv:ICgAzQMvKPZY+Vlq4ydGtUn5iLps6vYtoo9X4P1AMMc=,tag:+zJki5wTvdJAu3BcWQOI2Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:fli6dvR7vGAlPpOfgDM9FLA=,iv:+5npzgffAJzbnTZa7KP32nG/eY0O7KapQni8o3IqpBU=,tag:Az/N1oAdkeqIIg9OLyeN4w==,type:str]
    namespace: ENC[AES256_GCM,data:gifLumNpBlCb,iv:PNPPPL7c0oV61VOhKgHHnRUjgG73m9ET+SpBYnTfz5I=,tag:hUeIkiYOzBtu9PEJHzE2lQ==,type:str]
type: ENC[AES256_GCM,data:AF79YLLs,iv:R/lwVXaH/GBCQBja8DLJZasTOt5wto0GAsHwAxxVNZ8=,tag:J3DteEWViSlwd8eigRShuA==,type:str]
stringData:
    admin-username: ENC[AES256_GCM,data:K/fUgnw0+OjK1NiezbBv,iv:17n+HfK1JKcFgzlp8PPh7j/AWjvPLQaiEUTUD9U+QQ4=,tag:s0cs/Z1Rrny5PZ9BoYEohw==,type:str]
    admin-password: ENC[AES256_GCM,data:6oeyMi+9ELy3+atxhcL9VA==,iv:LZoInL8gcgQYkpuIGdmp1zX969Bk2uM+J95ePNfw9sI=,tag:MojJ7ZOuWvPBdJ32cWJKsg==,type:str]
    admin-email: ENC[AES256_GCM,data:xMQqTNR+2e0NFI2uNCWO6LDI9JIDtnrF,iv:HsgN2otoHhwguCEropMAk341jIMhebCq1bK1/l78Kdc=,tag:5i+zYqfkx2EsQ6e5os4hMw==,type:str]
    admin-fullname: ENC[AES256_GCM,data:kjNNMd+MwzmwG50VaFge,iv:Utj5HF6n/+5niYJr1Vm5qjmBp3prZPmFJ6HyF51jrbA=,tag:xqkYIncpRXVOUW7ISJ8X1A==,type:str]
    oidc-providers: ENC[AES256_GCM,data:Mh32OVyriPIQvC3MsCUSaAiOVGNuG+lJI06ZESg43s/bjEkDeoknlF7Kq5QPhNrRZAkUMpCh7AryomdSJPdM6s/4hHjgj7ZfCxopaP7xCOp+qKipvhkUnz+u2jwBvfIopjdb+Cgch+0z6j0xA9ZeWTHfvOFTaReJRS1/5zg1s8YpqewmWvE+g6b8FrBpSJ+TUH0SBnwVg0h18SJ8mP7bct5Z8vEEhkB7REAVD4CNH/jUoSWEoLwehq1ocMiMImLjOjar3G4M1e4XbjLICrvUYC2BGd0JwXjHYPdEJleFADyZbtTjoDqfJwOo1uo9axwOhVWyNiblAlZ6AUiwvQdHR8wQ2dNhaH8E3ZrzVNxNS9gFPKMOZpXj6gTcqKC9THrS2I4OQPhnm8/Tp4gkTqoh8QjGp4EXgcXIPPnWTWUKo1R8cfQG6AjjBPArq08NNWglYzUPmtzYSN77ruFMBdzjMR4s/OaX/ZI1xucv1WwuZRzIiCfxsQi6AaYVbGacVtI5dsGLlNldqohkY5X75hth7aD0CKXao8EWX5UrxV874CjCJGoydbMl6HOrlqFD4s8lkYKnxzznaww9JcUKhSeNwllAZo6zVWHw96B0Ia/WaoqXnsCqa791YuXghMvSiPnl43rO++Y2hawc9HaRyQY3BTTGpo/pj9OWicvUmBqGVQ5mtV7ontcq2h/CN/enVboyCd4Bbio07p0=,iv:NPt4hVdgvgXBTeasAbV2nlQ9DH4j5DvSA5aE7sF9qw4=,tag:6ai6NEl1jCYKBeFGwANmdg==,type:str]
    password: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaC9heXpOOWlkaUlNTHV5
            Vms1M1JSL292bFRRQWJzOVFWVGQvVEI0VlRjCitLTHNOWVRIUFFWMDh2WVBYcGpZ
            WXQ2ZVJQdit2OGt5d1hSOHg5bDlBUk0KLS0tIGlxeVRkcWZ3bitncnZoY1U3RTNJ
            NWVYWUJ4YUJoNCtoZDY2WlZlQmRNZmsKfGaqL5zUCDHenN3ul2QG2MrrsYfOndt5
            m4+ad1urCBCbwb7EUii03HTY8bSkIsOuqSSHJWaT7ziBX2/d4xHyoA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pht0t0fr9gr8tf2vqm5y4s8lrg6g2xtql5m2xgzm4lv38mhaqfsslekwsa
    lastmodified: "2026-05-27T17:36:29Z"
    mac: ENC[AES256_GCM,data:0jXFYfyi3fZ2vZ7Xoj/uvR6djIcPlgwmXeHms73eWwgDj7U0oyoa4naRaSYSyVRdUZnkt373PeRS4/3hZ7Jee7yw64qnbQjirQuxT6V2xoQ1RcDydUVR8LoZ074bCSFNDQN/F/Z0Z/xe47ehUWtyGMI7/cgwTMkbBsmgGy5/T2w=,iv:ZnK0v3Hpkz9sPV+du1fDO3ErHYyxu1gie7S+H0xB8D0=,tag:MfhVEY/GHX/kjP5knUt56w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
