apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: music-bot
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"
    argocd-image-updater.argoproj.io/image-list: music-bot=ghcr.io/ryyyyan-taylor/homelab-music-bot
    argocd-image-updater.argoproj.io/music-bot.update-strategy: latest
    argocd-image-updater.argoproj.io/music-bot.pull-secret: pullsecret:argocd/ghcr-credentials
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ryyyyan-taylor/homelab.git
    targetRevision: HEAD
    path: kubernetes/apps/platform/music-bot
  destination:
    server: https://kubernetes.default.svc
    namespace: music-bot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
