apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lavalink-plugins
  namespace: music-bot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 200Mi
