apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ryyyyan-taylor/homelab.git
    targetRevision: HEAD
    path: kubernetes/apps/platform/authentik-config
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
