apiVersion: ENC[AES256_GCM,data:I+A=,iv:qnY9BWaobqhxVVYAQ+o8IJMk6sWLF4/pBH8gC933NKg=,tag:iX83clRYviTa/ra8ogZLKA==,type:str]
kind: ENC[AES256_GCM,data:cQ1jWlfb,iv:+M8JI0qkunD0AfmXfe+KqkTmvNmKT9mC9Gv5jat8Esk=,tag:/sdT3/oS4XdrM8BTnsMzCA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:X1kxfC0X1SRRV3yE76HFyqo=,iv:7GO2VWv0fKS2Gtt2jr8ZXAaWocaq0oqoj6qJ/5vtjVE=,tag:VRcRu9GhZ+4+HjsFPgF06A==,type:str]
    namespace: ENC[AES256_GCM,data:KKVbAB5aahJ0,iv:WNP72YD9tt2I7sZ1BrC5Iar1+8sTDFEO5ibxe1oBY4c=,tag:HW83GVNP6knG5US0aeDK8A==,type:str]
type: ENC[AES256_GCM,data:TvceX9eV,iv:RlmTYq7w5tjlS2p3Xtk+KT7xV1MKhbnUC5+lgnQUQrk=,tag:jCZAj6gaQkbn+AwG1M3wZg==,type:str]
stringData:
    secret-key: ENC[AES256_GCM,data:YeXOOqLnK6DdpyCsdE7vCl49MjXX/CEINcy2ldxGfIMWZiflNTFhfdWYYtZqJvN5FzrL0oq3DQ457OEhgMR8eA==,iv:ZXpUXXooucYIN5geIKqbjz47v49LJNZaBk4XSrAECV0=,tag:oy8165hXuid/NTizI6cwBQ==,type:str]
    postgresql-password: ENC[AES256_GCM,data:zzdrej24oRRrJiLbJ9aQjUzXJbkc6S8qVdV+vSCLEmI=,iv:OO6lKfDu5APvy82Bw/dNpw9osTlOf7GrxrVPCF9G22U=,tag:bGQzSC4DMPbcL1kWdwLthA==,type:str]
    postgresql-postgres-password: ENC[AES256_GCM,data:bOAaga+6XwVLxDbUVcR93lDXLxOHOQXsuZ9ApTx8Bkc=,iv:UUsURXcanXIbyIVGJ46x6XnxxHTIownn4zf9hry8QtM=,tag:7STJWRrnlFPWJiNW9AE06Q==,type:str]
sops:
    age:
        - recipient: age1pht0t0fr9gr8tf2vqm5y4s8lrg6g2xtql5m2xgzm4lv38mhaqfsslekwsa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbDhuSzc0N1o5YU94ay9L
            MUVoYlpaekFNWHNSZkIrbThMS080eXEvR1hRCmo4dGJYVnBvZVlCSzdySEEvRS9D
            YlVhR0xIRzdwV3JLL1dmSkYrZ1B2TTQKLS0tIFhGVDROb0V5ZFdSbEYxZXVDa3Yr
            bldaMmhPdjFXYTg2MHZsUis5MWxOSnMKWz0lQJ2ascqevinzPMcvpgK8vk5Lk24g
            w+YYoNAlRzEa8tjKBgn26F5AQTe620cOFozGtAao8ijf5a0A/57t7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T20:33:59Z"
    mac: ENC[AES256_GCM,data:DLuy4PUVCKJYz6C8qFVAl0SVZ00hPR3TxsqdIn+S6UvhdUoli1l+A3CXXQHHRRQ5xf/nbaVzG6CIuLMroz9zOmim2ixvL/ghkA+BDbKsNVyH4nhMNzrrAFtgHe4ZGLgdmMExn8Oq2+W+TM6Y2+80+lDDmVaxpl+1iFnK7+bqXak=,iv:Zi4daMYJ0Lqs2VcDvo5L1OKxg8XKPTcO8Dv4rvbN3cQ=,tag:tGUPRixoSWg6YaQbvM5zdQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
