apiVersion: ENC[AES256_GCM,data:B9Y=,iv:d2vh/0X3HYWS8I8HasY3h0OjPvkB2xg5ibZgW3/D6MU=,tag:ltKSTTkV3nl+WTpuV+f8/A==,type:str]
kind: ENC[AES256_GCM,data:k1IRtHxw,iv:8In+OAYAAPvKhmQJpvcPPehpk2dXeH9RDl/Ux5738zc=,tag:/f2tFM7/hyqZKlEjnu/AeQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:79hcrjAnDPPasMdfL2OWMPV935eS7dHZM9rulg==,iv:7OhKmjPIjKyF4ErUkRrOXjbsMPRQb+kgb7u6rYEEFRE=,tag:8L4XqUlp4zdxiRPakZoNrg==,type:str]
    namespace: ENC[AES256_GCM,data:kVJ0ORFNKHmX,iv:YOWcATdYE3exWvozxNcf0knLCj8BnxT6b2A97PFN3Kg=,tag:0cizUv2hJfn3EbwRKx9z6g==,type:str]
type: ENC[AES256_GCM,data:iWk+jenQ,iv:IIuzSVLINKEJuq98SmK0H4dBiKuhlpeXWc7XKnCpdoc=,tag:P6jTKdECFnbhF5Wt9DT0sQ==,type:str]
stringData:
    token: ENC[AES256_GCM,data:fiSVwWrTnk32tbazo/d5IxAmdzb9Tpfq0oeXvk2hkzqsdJ40TAX6XE/L3Sd6g2yFH8wTrrCfvOchGmzU,iv:xRhKc6vVFUVl+t5PMmUSZcAesRMz3wFhX/gjWF1XIkM=,tag:+2B51AVUUIuzx/jaMKezKw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMHF5czQ1OXhGbHBjdm9K
            UGs0Y3JpYmFxRS9Ualh3WE4wb0xob0hiTUdFCjRab3dYaFlyeVE1UTMzSEx5Vlc4
            MXg0YmRHcHpFVFVMa3BMWTZvZ1h1Z1kKLS0tIDZJMmErYktIRGJlcmJadnJIeVN5
            ZUNVK1lLcm1selhqb3NLajQ1anRkNmMKQDm+aaE3unZUZ+48071wkc9LUsTXjAgV
            aWCYgP9eDUUlD16aYG0xJ4nqJWjss6/FD9d7ZOHFni0crN1X0cuUDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pht0t0fr9gr8tf2vqm5y4s8lrg6g2xtql5m2xgzm4lv38mhaqfsslekwsa
    lastmodified: "2026-05-24T17:32:55Z"
    mac: ENC[AES256_GCM,data:iDMaYb8OYzvh6HBJvOMoK6hTTOgCQdIlOSSwgzZVziJ9YVXR+dtVuIyQV7t0X1kM991fvyDS/MS/E6Bm1LwQn1wLCawMaSpvUZQmIGm6B4hBOI0z8F4xaLboOWMgOHrda4IsjvXQTf+LhnL3XC6Ax84TJKdCgay0oqO7Zgy3qT4=,iv:kBXhAOV3q50pXa9EFBNqILteF2k8SLloefzaZXBkL+Q=,tag:0Kc+Mc+uSxdeuFb/pWCQig==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
