apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: open-webui-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - webui-secrets.sops.yaml
