apiVersion: ENC[AES256_GCM,data:u3M=,iv:8VZqxZgp1m9Xjd2aJ31uEp0yRhLTSrswlYmIM4RwXYw=,tag:OICfFFWHUcJVK0BmF2QMyw==,type:str]
kind: ENC[AES256_GCM,data:Xx1iVvtK,iv:knpAzc7Qy5ohmVlqeUfSHqTIAbLTTuAdM9aQBvwrs/Y=,tag:FU2+gRichiWrqFWt/kgm/A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UCLzA5mITrXfnwHA7MrRRM7M,iv:fgUrXzpBffEYXGfbs8MUVTvsVi0GY6P0ju6bao5V188=,tag:4FWRvkB5gCMdd3I23VsHkw==,type:str]
    namespace: ENC[AES256_GCM,data:fG4DdpJovWeTJg==,iv:gXadS+K2faBBVVj50R6UiGP5BbG43iCs7xmxVR5/Prk=,tag:32Xramkey/zDGHE2k0BnGw==,type:str]
type: ENC[AES256_GCM,data:A3Rs9Q/a,iv:6UyMqDexofAXSzb0JPvjDcE30s66jujImooY+pRXuIw=,tag:122/vdTgsiaoejq62wCXjg==,type:str]
stringData:
    webui-secret-key: ENC[AES256_GCM,data:g1j7+dTXV+sraG1C2sBvYROqshh2NMgY1KaHqbNl4Pl3+N3RRijyxjmSwimvmDWI/7U/CudRnnpBSlF/3OwDfQ==,iv:FFO91wsbl56VYBtOwVayNJGewRcKgPgnemy08EAob3g=,tag:ClgqQWpXBUnJPbOHfhgKPA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxL28vdHl0TTkzTklQRGhX
            VDNUUzV1bmM5NXBOcytoRU9GbU5KQVhwYndrCndkN01Yd0RWelhodU9UTUFkVXRE
            YTBDa2tDVzZJbjdXby8vOVF1b3Y5em8KLS0tIG5iTmZhb3ExR3VYWEppNWxXVW1D
            RGd0cGZlVld2cE1wQ3VwdmRPa2d5Z3MKGkno3yKekB37OXo8lK2mrCvKO3smZ5JQ
            +OngBJYkMZmwdkNxGSDhKMC1MZJB7sxbVH7xr/oZPrTqCGohECuXwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pht0t0fr9gr8tf2vqm5y4s8lrg6g2xtql5m2xgzm4lv38mhaqfsslekwsa
    lastmodified: "2026-07-31T03:54:59Z"
    mac: ENC[AES256_GCM,data:44QZwT58A+QJrtPRbE6BJB3c0gcy2ia9M0I3JfnThzuDZP/CJ8ZzAoVgj3mGhhsVl8wSY3Cb4v4s4ZE8rPD7RF4yvVGiBmDA8gOYP+bFquW7tcIk+FjjEbhDLjga7wPJ+egKYLF44dQ70MQ4ajeYMGvMgjz6/QKKqk+NC2rNJoI=,iv:oG1+6km3rV6iImhoi2WCsrbyFHw6EVek49YDBBLSHHI=,tag:Ex6GjalDmj5Xp01EAJ5EBA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
