---
# Server settings (ServerConfig.json)
ck_game_id: ""
ck_world: 1
ck_world_name: "TheBoiz"
ck_world_seed: "0"
ck_max_players: 100
ck_network_send_rate: 20
ck_world_mode: 0
ck_season_override: -1

# Sensitive vars — defined in group_vars/game_servers/secrets.sops.yaml
# ck_password:

# Admins.json
ck_admins:
  - index: 1
    privileges: 2
    name: Banjo
    steamId: 76561198079928331
    crossPlatformId: 0
