machine:
  network:
    interfaces:
      - interface: ens18
        dhcp: false
        addresses:
          - 10.0.1.201/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.1.1
    nameservers:
      - 10.0.1.160
      - 1.1.1.1
  kubelet:
    nodeIP:
      validSubnets:
        - 10.0.1.201/32
  install:
    disk: /dev/vda
