ldap_bind_password: ENC[AES256_GCM,data:VmJyVbjDjVQtwY6+DMgK4kPMmOQq2QFf9b6L0BUQqV9d6LXG2P/sb23P5+WkSLFqWzl1mZbtacuZnHDY,iv:QABkMfHek15Ul+9YlGJPN7AGx7X3tDUKPZFaWJmnu0Q=,tag:M6XQ1sdsL09jyDdsV3Izxg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UFV6WTZ4ZGlZRUZOVDMv
            M2pReXdGMk8ybnFoM1c0VDRWdHhaaXlPVVNZCjUvQ09yaER5RE9OS0ovTFY3RnNN
            Tk9qdVNiU0daZ3FXcEZWRytnU2k0bW8KLS0tIGo0TG9Ta21jMFl3eUZUNW9iNjZu
            dWJCVXFHcHY0MzJxSC92RVZpMkdZaTgKxuqZdNPHE2SjpsVxxr53snL0kmQ+AoxV
            /nnrRIA2pz8jesC6A+hMwvbX57nFJQt1BvtfvnbW/8ji85vmIoJyGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pht0t0fr9gr8tf2vqm5y4s8lrg6g2xtql5m2xgzm4lv38mhaqfsslekwsa
    lastmodified: "2026-07-30T23:57:42Z"
    mac: ENC[AES256_GCM,data:fnPJEbMEB7cVuBXksh7J68DD5Qzx1aN5Z9M4gj1jSguR3MSjsMI6AbhdKWQ9VkVi5GpwX4880bCN2U4NjrbxGwefTUvbqhNudYRLi8fKQozo8P/hgUMaVvcWn6JCZZzSB+SFflHs1lyTExSu3dHF8erAq45L8RVHYXPPXJzV4rg=,iv:hoqCkSDfbo/+nSS1I/hh7m9fLqIeJUlg/aP26FG7VvY=,tag:cumf94u9BwHwSK68ePaX3g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
