apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - platform/cert-manager/application.yaml
  - platform/cert-manager-config/application.yaml
  - platform/metallb/application.yaml
  - platform/metallb-config/application.yaml
  - platform/traefik/application.yaml
  - platform/traefik-config/application.yaml
  - platform/local-path-provisioner/application.yaml
  - platform/authentik-config/application.yaml
  - platform/authentik/application.yaml
  - platform/whoami/application.yaml
  - platform/ntfy/application.yaml
