apiVersion: ENC[AES256_GCM,data:870=,iv:DsR6R2hnm+4f9QNPafKzlGO5OeJ321wHtwnERNQ+OGc=,tag:Wm+HYq3/7NvRKm4b5/gOqw==,type:str]
kind: ENC[AES256_GCM,data:Fukat5KI,iv:/UjyZ/S+quTdjAmU4To6AT/9T/hAslyKZxucZh2nSuI=,tag:0hXXeq5ih82yRt4h3UF+og==,type:str]
metadata:
    name: ENC[AES256_GCM,data:y8rwTdyf3Wl66PBQBw==,iv:hxyTLSs/wm6vq3Vtgh20+/jS/t+N/C6rz0Z3KfeGmgU=,tag:3iOsQUHpPLZjQ/YyrCdaOg==,type:str]
    namespace: ENC[AES256_GCM,data:5/pHYX0S,iv:9CUltUj3rAdxQk+kP/e4efSOs//Dp4rc2G0SYs4wpfQ=,tag:0rlk9VSskN5abWpZ7vC80w==,type:str]
stringData:
    oidc.authentik.clientSecret: ENC[AES256_GCM,data:iURE0YUkNHH65xLq9Ffi5Ld7AaL67qbzY3EYdsq67JxClPH9Wr18rQqNmZBJh3fShCySICC6cCBz9bdrLsPu9SkwE6AiWfJgtU1U54r25dnoF05oDlIGM5817TxzoldNui+iy38BeRVpL8zh5dXJnB+zhmz40HYI4otpi6y6SUk=,iv:MowSpSyZ7Vjwt0Yi4NIWIcNlJsEIbSHDRWmvFxM1ehg=,tag:GlsXNTKFShTTusJLhQm3wg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZK1Z4THVpWG5OK2FRWHhE
            UEIzaWlWdjhDbDR0NWhzM3BjRTZ1Z3pobEhjCm5tV2dCQ1ZzSmxtazcwZjRub25J
            UGY4SjVDb0ZYc1NaWVNLRHFvQVNXTjAKLS0tICtqdVZEaHlvNXAwaEpmRUIwYnRY
            UmdpUmJlL01qblJOamlORXZ3UVJWa2sKel1TEzTGU4MIjp4q79aVD0bS1f8qOlIZ
            ecmaH+uVdVF/p2qRBlgrQ1UWKkInLSfFhnufL4uVpLimfgWF7mYSJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pht0t0fr9gr8tf2vqm5y4s8lrg6g2xtql5m2xgzm4lv38mhaqfsslekwsa
    lastmodified: "2026-05-25T16:42:10Z"
    mac: ENC[AES256_GCM,data:qoXACq/CJU8iQRFzZCQLEmWQEd+H/9EeVpRTbfyTkAPyTIZTe67OQrfwuA/p1vMHZelxBXz6jGCONETMj9UsOO7DIboTUtoGXxWWHYH+gPTqJNopC8HKqKX/7soAF+ltX8ADekZFwsHUMQ1u5I1iPsA8sVZY8LlugShG3hjOe3k=,iv:+yTwRamIb9kQybB+JjCH08ePQ9Nb2qWRqa6e3QxRUxg=,tag:svmgaoHPCxJIKkBfaUnU4Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
