apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  admin.enabled: "true"
  url: "https://argocd.lab.ryantaylor.tech"
  oidc.config: |
    name: Authentik
    issuer: https://authentik.lab.ryantaylor.tech/application/o/argocd/
    clientID: xbs2gD07ycch7lvHuWj0UFeYMei6tNOajHREBoMD
    clientSecret: $oidc.authentik.clientSecret
    requestedScopes:
      - openid
      - profile
      - email
      - groups
  resource.customizations.ignoreDifferences.apps_StatefulSet: |
    jqPathExpressions:
      - ".spec.updateStrategy.type"
      - ".spec.updateStrategy.rollingUpdate.partition"
      - ".spec.persistentVolumeClaimRetentionPolicy"
