apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - certificate.yaml
  - tlsstore.yaml
  - dashboard-ingressroute.yaml
  - authentik-forwardauth-middleware.yaml
