apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: music-bot-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - music-bot-secret.sops.yaml
