apiVersion: ENC[AES256_GCM,data:ckM=,iv:0KBIoVDarSSy7tlkHdf43TVOV6JijDnNL/5xR8X1A4k=,tag:lrpwXcMncD8D7oVXPMh9Bg==,type:str]
kind: ENC[AES256_GCM,data:MYQvIJOL,iv:Wka+9B2S/J7bC/hqb4lG4PiLGtPJQ2XFK3HSlnBcGb0=,tag:XsI8T8j2aFcYspoM1tTllQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:APgvfbvB8LKBTolSCtHBsQ==,iv:FaWf1Q8AAdI6yQJ/wIpRSjyq3fRwl15FYKqKLDwl0Ys=,tag:Zw2HnFNRNv0JDBqahjsZmg==,type:str]
    namespace: ENC[AES256_GCM,data:oY/j0+cfRtMF,iv:F7ABWb2BuryQub0/vgl9wIPBA0Y+kPQB75fvdZKnNq8=,tag:g8vP37ub5Ir983M+u9YmCw==,type:str]
type: ENC[AES256_GCM,data:oPBfclCh,iv:TVFy/FA9219B72fVBaLMabJPqx8lZNAKdprfSpWvDuA=,tag:t6F8l8nDFhZ1lAUUPX2rqA==,type:str]
stringData:
    lavalink-password: ENC[AES256_GCM,data:Y6Q46j4CeGhLESYCTJE2BlZrG6INll/wHY7zSNOh2JMKiLyTPyv4HttBQ5TCU2zMRSW4q+KxAg1kV5HVRH4Iuw==,iv:58SnktwssnbjRSgHavy+9lKBAkv7y4Id9JP0dZRGHnw=,tag:/13xl9YnKFZCNrEIGNFYng==,type:str]
    spotify-client-id: ENC[AES256_GCM,data:QQCgd+v64M34fk0rS1dh7i+wib76eXjZ4OrUOFIjUuY=,iv:eYF96dQ/046ftUnkEUfXr5ETnqNPS3DckyhpDLczIUE=,tag:PKy8KODGL4fzoWU43nIuZQ==,type:str]
    spotify-client-secret: ENC[AES256_GCM,data:br8dvZ6+98fNLjxLQgMge8O2f+Q8NTaaPBYKtQKxR/4=,iv:ED1V4k1/xtNDOcMmt3zqcvkCqqY2V5Ad5hKk0Wiz0CY=,tag:ifZbKEbmL7C6jx2cT/95CA==,type:str]
    discord-bot-token: ENC[AES256_GCM,data:IJKXZLOOcnmfy6rknIrkl9z1t6PlcruxF9pnThIQqej66NF0cxDbP0bGRSHZhw6LoEhxgKHBOidQpTanyyBCpY2KcDnOo7C1,iv:exbQtiryahvfX5re27XDvuAiLPTZfYmsj+HFXLH9TAE=,tag:LAmr+vtjQB3i0bGt9vJNJw==,type:str]
    discord-guild-id: ENC[AES256_GCM,data:GQHt8B6YfyED/T/B2DyjYQTnzA==,iv:hAfCihySoxuUJGujh71NnAwf7Q7VYiAjaWUHWrjAnRk=,tag:6VxxPNoRGakkm1jp3nKzUA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLblozQkd3dVQ5OVFzOWhH
            UHoxLy8xQ2UrNkcvMGs2NmZQZWJrc1pwR0Q0Ck9oaERVRi83emVpK1hCSGxkbHlL
            YWdCVm1uYnlnWHVKUUsyL3k5aGJ6MXcKLS0tIExOZnJSOU5FVE1vNGxJZ1U1NEVs
            akt6QkRKZjBFekdjcHc5ZXRHQ1dtdTAKlwmDnrglVVWSMG8ZrCbLiXiK7ny0wyOQ
            8As+QBhafPk7VleVG50QcZcCH6qGGofj+xSMNgCaS3ZYZ1kF1LYJUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pht0t0fr9gr8tf2vqm5y4s8lrg6g2xtql5m2xgzm4lv38mhaqfsslekwsa
    lastmodified: "2026-08-03T17:16:09Z"
    mac: ENC[AES256_GCM,data:wi+zb166j6PYUZepLGGtnqysDfpyBtfNFrElG3pQV/iOwJV1+FSGbuY1iM+yPSGCZ+OOinejrkBG6eDL7L8fX12YeEElvNWOFhRvqSN8DvLgTZioceFR4k5DBJXNXpFZhwCCZVdYSsZvaJ7YuU5bar86VjdsQpT+2NW2FVYQLeA=,iv:cnZCbCC+zCP8mELgCQdjAIv1IQLAi9gCla8774BxxZ8=,tag:qbmbHzzHbHybnutN1tnqAw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
