apiVersion: ENC[AES256_GCM,data:ckM=,iv:0KBIoVDarSSy7tlkHdf43TVOV6JijDnNL/5xR8X1A4k=,tag:lrpwXcMncD8D7oVXPMh9Bg==,type:str]
kind: ENC[AES256_GCM,data:MYQvIJOL,iv:Wka+9B2S/J7bC/hqb4lG4PiLGtPJQ2XFK3HSlnBcGb0=,tag:XsI8T8j2aFcYspoM1tTllQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:APgvfbvB8LKBTolSCtHBsQ==,iv:FaWf1Q8AAdI6yQJ/wIpRSjyq3fRwl15FYKqKLDwl0Ys=,tag:Zw2HnFNRNv0JDBqahjsZmg==,type:str]
    namespace: ENC[AES256_GCM,data:oY/j0+cfRtMF,iv:F7ABWb2BuryQub0/vgl9wIPBA0Y+kPQB75fvdZKnNq8=,tag:g8vP37ub5Ir983M+u9YmCw==,type:str]
type: ENC[AES256_GCM,data:oPBfclCh,iv:TVFy/FA9219B72fVBaLMabJPqx8lZNAKdprfSpWvDuA=,tag:t6F8l8nDFhZ1lAUUPX2rqA==,type:str]
stringData:
    lavalink-password: ENC[AES256_GCM,data:RPiYZL/L4vLRRXTepditdPIZ5fNU/0clT3CF1NCPNoG1JbX5DiB/Uiet30AwUuSpeJyfQFOdmnFJw2zvWwjC/Q==,iv:nKtSGhbPNeHj/8PZ7SaJ4ZSCCHvZpWWTh+Mk0iDbXLU=,tag:E4+YNok32cWxZhMrtZvKeQ==,type:str]
    spotify-client-id: ENC[AES256_GCM,data:Ahv0N05c9XW4Cf/fFab0jqhzz44IFDDrpKifUyonnOY=,iv:tdPdE0s3xgkEANv7JFIMDbs47BpJtPypOMqv4nSe/Ko=,tag:ztZP03x/FByw+PBpRISteg==,type:str]
    spotify-client-secret: ENC[AES256_GCM,data:RCvpBrOALifV3kyJpypRKNLP+G6bdTzMsv7qUatn28g=,iv:N4opg1I57qd3maqyRD/wrJ000dmM/FWaFh3w5CCIlfU=,tag:A6ouOIyoF8Vv+voOjpQQgQ==,type:str]
    discord-bot-token: ENC[AES256_GCM,data:OpB4nhe+paG5YCzOgXsrCbigfw2YBGvpc36cSK1+/AIByGYXMUskppEdOJj5VGjH5fyLGpKenTl2IRiWf6lGsWu1CvKIhiag,iv:QEvJLbPFMvCzoxich4gpn7rIJa70IQU2mXmeMgx0fKg=,tag:HTdGyILcWKw3aaxalFTIwQ==,type:str]
    discord-guild-id: ENC[AES256_GCM,data:VCl4wPV/TIETQeDE1pv9E/thXA==,iv:oERu5PFSD1i9xmauwmRYLolL3k1pnzQnTvAFajhZM84=,tag:Jos7JbK3IAvJTYiu3uWqXg==,type:str]
    spotify-refresh-token: ENC[AES256_GCM,data:h6tyiJwtGaQle0AwDgLSfHIC3qzNF8AFp3d1xOxexfVXnbGLcUt/i5jbCAudAmHmc8zj4TyWhJgelVM94Vv5jFrrYpeXAjed/DJ6IUUZALcQ3k8BvuEj56QoMw2kHZwixrrbWuY6Y1tR9nw6RgfY6eWBS+914LIqGmiHns8yUXihqTk=,iv:8bZofZIme/IOBi31NocPm3YUVHv9a8Q7m4pUDrM+kAM=,tag:ocdbV3xPWuYNuUFpEWwtCw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLblozQkd3dVQ5OVFzOWhH
            UHoxLy8xQ2UrNkcvMGs2NmZQZWJrc1pwR0Q0Ck9oaERVRi83emVpK1hCSGxkbHlL
            YWdCVm1uYnlnWHVKUUsyL3k5aGJ6MXcKLS0tIExOZnJSOU5FVE1vNGxJZ1U1NEVs
            akt6QkRKZjBFekdjcHc5ZXRHQ1dtdTAKlwmDnrglVVWSMG8ZrCbLiXiK7ny0wyOQ
            8As+QBhafPk7VleVG50QcZcCH6qGGofj+xSMNgCaS3ZYZ1kF1LYJUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pht0t0fr9gr8tf2vqm5y4s8lrg6g2xtql5m2xgzm4lv38mhaqfsslekwsa
    lastmodified: "2026-08-03T21:05:32Z"
    mac: ENC[AES256_GCM,data:8X6qSypdPMee6Uzuqp9yHk2uF44BNI/+e/RcZX9C/ciedN6ect4VMouPppo1L0TBR38Mf0Qlk8kyLShO3CYnnYOE4KQoHXAMeK8lh6/WgRimtCH3ngf5zCJSo51k19/dn+a4pUm8MewN1LQsW+9pqVg870AfmBIQVY0LU13rITM=,iv:Mk/KCyK3cYCNCfmRMmXMP0pXEDCVx56j6y3yJaFsBSM=,tag:JN5u51KvFieLnN1QPVmFMg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
